version: "2"

linters:
  default: all

  disable:
    - wsl
    - varnamelen
    - gochecknoglobals
    - godot
    - gocognit
    - cyclop
    - funlen
    - funcorder
    - nestif
    - tagliatelle
    - forbidigo
    - copyloopvar
    - intrange

  settings:

    nilnil:
      detect-opposite: true

    revive:
      rules:
        - name: exported
          disabled: false
          arguments:
            - "disable-checks-on-constants"
            - "disable-checks-on-functions"
            - "disable-checks-on-methods"
            - "disable-checks-on-types"
            - "disable-checks-on-variables"
run:
  timeout: 5m
  tests: false
  allow-parallel-runners: true

