name: ci

on: push

jobs:
  ci:
    runs-on: codeberg-small-lazy
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v7
        with:
          go-version-file: 'go.mod'
      - name: Build
        run: go build
      - name: Lint
        uses: golangci/golangci-lint-action@v9
      - name: Test
        run: go test ./...
